domain: nmcain.github.io
url: https://nmcain.github.io/gaming-journalism-blog/
baseurl: "/wind"

title: Wind
email: wind@example.com
author: Noah Cain

lang: en

plugins:
  - jekyll-seo-tag

color: "#ffd600"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
